### ISSUE TITLE
Cannot continue if waypoint already in view

### ISSUE THREAD

**Issue by ssshake** [scaccogatto/vue-waypoint#21] opened 2018-10-12 18:40 UTC
OK so I'll try not to butcher this explanation.

On waypoint I make an api call to return a list of items, then render them on page as a list or rows.

As long as the waypoint gets pushed off screen, then on scroll the waypoint is triggered and more data is fetched. But if the waypoint is not off screen this can never happen.

So this becomes a problem depending on screen height.

Lets say my api call is returning 3 items (small to expose the problem).
Lets also say my screen is tall enough to render 9 items.

What will happen is on page load we fetch the first three (as per my created()), 
Then because of the waypoint being detected the first time it fetches an additional 3
We have 6 items on screen, which is not enough to push the waypoint off screen.
Because of this, infinite scroll breaks as there is no way to trigger any further waypoints.

Am I doing something wrong or is this a bug? The documentation seems simple enough where I think I have done what I should.

Now if I set the number of the results to something larger like 10 items, then waypoint works fine. Get's 10, pushes waypoint off screen, scroll, trigger, fetch, repeat.

However I guess I could argue that this same issue would happen if I had a very tall screen.

I could see how you wouldn't want to continually repeat this trigger if waypoint is on screen permanently (maybe youre at the end of the list / no more data). So I'm not sure how to propose reconciling both situations.

**Comment by scaccogatto** [comment] 2018-10-13 14:35
Well this is not a waypoint related question but I want to help you anyway.

This library performs a very specific task (something related on wrapping IntersectionObeserver API) and everything outside this is just more logic on top of the library.

I see some logic fallacies here:

> We have 6 items on screen, which is not enough to push the waypoint off screen.

It is good wanting your page load only the required data but what is, in your opinion, your required data? Is "required data" enough data in order to cover your whole screen height? Or `data >= x ` is your requirement?

If your requirement is "enough data in order to cover your whole screen height" then this library will work as intended as long you handle correctly your fetch logic. You should have and endpoint (let's assume `/data/list`) that lists a reasonable amount of `ids`. This `array` is what we will reference later in order to get our data in order, I assume `/data/list` is correctly ordered as you want. When you have this you have to load your content by chunks, one chunk at time, so you won't load unecessary data. Your chunks can be from 1 element per chunk to `n` (facebook's timeline should work something like this). This method allows you to have only the data you need and ordered as you want. It requires you to build some kind of chunk logic but you should be fine with `Promise` and array manipulation (maybe a bit of `Array.reduce`?)

_I did this personally and it works very well under http2 context_

If your request is the other one (and I personally think it is a bit lame) you can just use this library deactivating when you start any kind of data load and activating it when your load ends. Your waypoint trigger will start loading the data and set a variable to `false`. This variable will be used here:

`<div v-waypoint="{ active: YOUR_VARIABLE_HERE, callback: onWaypoint, options: intersectionOptions }"></div>`

This should be enough. I don't think I will reply again to this because it is not an issue but I will leave it open just to let you reply if everything went good with your project!

**Comment by scaccogatto** [comment] 2019-01-07 10:43
I close this.

**Closed by scaccogatto** 2019-01-07 10:43 UTC
Labels: question
