### ISSUE TITLE
Waypoint doesn't fire on refresh + same scroll position

### ISSUE THREAD

**Issue by guanzo** [scaccogatto/vue-waypoint#12] opened 2017-10-20 04:20 UTC
I have a long scrolling website, and there are several waypoints throughout. The waypoints work fine as i'm scrolling, but oftentimes when i'm testing a particular section, i'll refresh the page, the scroll position will persist ( on Chrome at least ), but the waypoint won't fire. To make it fire, i have to scroll 1 page up/down, and then back, to trigger the waypoint. 

Could you possibly make the waypoint check it's position on initiation?

**Comment by scaccogatto** [comment] 2017-10-20 07:23
> Could you possibly make the waypoint check it's position on initiation?

The answer is yes, will I implement this? Not with the current technology.
Waypoint's definition states that it should fire when the page scrolls, if Chrome does not triggers the `scroll` event on page reload (thing that should do in my opinion since it actually scrolls the page to the point) the waypoint will not trigger (as intended).
Probably they do this for performance boost, so you should review your logic and follow that path too (so don't trigger past waypoints, just trigger them when you need them!)

So, if you plan to trigger all your waypoints to the scroll point you need to do it programmatically:

```
<my-section-with-waypoint-inside
  v-for="(section, index) of sections"
  ref="waypointed"  
  :key="index"
  @triggered="triggerOthers(index)" />
```

```
triggerOthers (lastIndex) {
  for (let i = 0; i < lastIndex; i++) {
     this.$refs.waypointed[i].functionThatYouTriggerWhenWaypointFires()
  }
}
```

Just follow the flow, if your applicaction needs a particular past status that may depend on user's configuration to make it happen (page scrolled + refresh + chrome) probably you have some kind of flaw in your App.

**Comment by scaccogatto** [comment] 2017-10-20 09:51
Also, you can force scroll to `y = 0` and then scroll programmatically to the desired point, maybe with a good easing:

https://router.vuejs.org/en/advanced/scroll-behavior.html
Scroll to 0 then animate the scroll to the desired point with some animation library (animejs?)

I am closing this.

**Closed by scaccogatto** 2017-10-20 09:51 UTC
Labels: wontfix

**Comment by guanzo** [comment] 2017-10-20 20:38
Thanks for the reply. I'll try programmatically scrolling.
